apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    backstage.io/adr-location: docs/adrs
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
